sudo: required

services:
  - docker

install:
  - travis_retry docker build --tag bodsch/docker-jolokia .
  - docker run --detach --name jolokia bodsch/docker-jolokia

script:
  - docker ps | grep -q jolokia

after_success:
  - |
    [ "${TRAVIS_BRANCH}" == "master" ] && curl \
      --request POST \
      --header "Content-Type: application/json"  \
      --data '{"source_type":"Branch","source_name":"master"}' \
      https://registry.hub.docker.com/u/bodsch/docker-jolokia/trigger/${DOCKER_HUB_TOKEN}/
