sudo: required

services:
  - docker

install:
  - travis_retry docker build --tag bodsch/docker-jolokia .
  - docker run --detach --name jolokia bodsch/docker-jolokia

script:
  - docker ps | grep -q jolokia

